theme: minima
minima:
  skin: classic

title: "Large Language Models as Information Extractors in Healthcare"
description: "Evaluating retrieval methods for LLM-based clinical information extraction using MIMIC clinical notes."

github: false

kramdown:
  toc_levels: 2..6
  auto_ids: true
  toc: true